### ISSUE TITLE
Can't run mvn pakage on java 15

### ISSUE THREAD

**Issue by havinhphu188** [shuaicj/spring-amqp-examples#1]
Solution:
1. Add prerequisite java version 1.8
2. Or, upgrade spring boot to version
<parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.3.4.RELEASE</version>
 </parent>

**Comment by shuaicj** [comment]
In pom.xml it already said that java.version 1.8 is required.
